#ifndef __LCD_ICON_H__
#define __LCD_ICON_H__

#include "kernal.h"

#include "LcdDrv.h"

//定义图标组合宏
#define ICON_ALL        0xFFFF
#define ICON_SIGNAL0	ICON_SIGNAL_STATION
#define ICON_SIGNAL1	(ICON_SIGNAL_STATION | ICON_SIGNAL_INTENSITY1)
#define ICON_SIGNAL2	(ICON_SIGNAL_STATION | ICON_SIGNAL_INTENSITY1 | ICON_SIGNAL_INTENSITY2)
#define ICON_SIGNAL3	(ICON_SIGNAL_STATION | ICON_SIGNAL_INTENSITY1 | ICON_SIGNAL_INTENSITY2 | ICON_SIGNAL_INTENSITY3)
#define ICON_SIGNAL4	(ICON_SIGNAL_STATION | ICON_SIGNAL_INTENSITY1 | ICON_SIGNAL_INTENSITY2 | ICON_SIGNAL_INTENSITY3 | ICON_SIGNAL_INTENSITY4)
#define ICON_SIGNAL5	(ICON_SIGNAL_STATION | ICON_SIGNAL_INTENSITY1 | ICON_SIGNAL_INTENSITY2 | ICON_SIGNAL_INTENSITY3 | ICON_SIGNAL_INTENSITY4 | ICON_SIGNAL_INTENSITY5)

#define ICON_PC_UP		(ICON_CONNECT_PC | ICON_UPLOAD)
#define ICON_PC_DOWN	(ICON_CONNECT_PC | ICON_DOWNLOAD)
//lcd左右图标和滚动条
//设置左边图标风格
enum
{
    //覆盖之前所有设置
    LSI_SET = 0x00,
    //在之前基础上关闭
    LSI_OFF,
    //在之前基础上点亮
    LSI_ON
};

#define LCD_ARROW_UP        0x1000
#define LCD_ARROW_DOWN      0x800
#define LCD_ARROW_MID_LINE   0x400


VOID STDCALL LcdSetIcon(U16 wItems, U16 wStyle);
VOID STDCALL LcdSetArrow(UINT wVal);
VOID LcdClearIcon(VOID);
#endif
